# Generated by Django 5.2.1 on 2025-05-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('complete', 'Completed')], default='pending', max_length=10),
        ),
    ]
