# Generated by Django 5.2 on 2025-05-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='amount',
        ),
    ]
