# Generated by Django 5.2 on 2025-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_price_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
