# Generated by Django 5.2 on 2025-05-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sale_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='title',
            new_name='customer',
        ),
    ]
